In [1]:
#Previsão do preço das prinipais açõs petroleiras da B3, utilizando LSTM e análise de sentimento

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import datetime as dt

from pyarrow.lib import Tensor
from rich.jupyter import display
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM

In [43]:
#Cotação das principais ações de petróleo da B3 (utilizando o Yahoo Fynance) dos últimos 4 meses, pegando somente o fechamento
df_cotacoes = pd.DataFrame(yf.download(['PETR4.SA', 'PRIO3.SA', 'BRAV3.SA', 'RECV3.SA', 'UGPA3.SA', 'CSAN3.SA'],period='4mo'))['Close']

[*********************100%***********************]  6 of 6 completed

In [50]:
df_cotacoes

Ticker       BRAV3.SA  CSAN3.SA   PETR4.SA   PRIO3.SA   RECV3.SA   UGPA3.SA
Date
2026-02-02  18.298454      5.82  36.737907  50.880001  10.641539  25.870001
2026-02-03  18.139425      5.99  37.073322  51.500000  10.855536  26.110001
2026-02-04  17.940636      5.82  37.014130  50.250000  10.524813  25.990000
2026-02-05  17.483423      5.64  36.501141  49.150002  10.388633  26.120001
2026-02-06  17.374090      5.77  36.155861  50.630001  10.466450  26.670000
...               ...       ...        ...        ...        ...        ...
2026-05-25  19.930000      4.39  43.400002  64.309998  12.350000  28.440001
2026-05-26  20.070000      4.28  43.439999  64.750000  11.900000  27.870001
2026-05-27  19.910000      4.01  42.820000  62.980000  11.810000  27.480000
2026-05-28  20.240000      3.94  42.509998  62.970001  11.580000  26.910000
2026-05-29  20.250000      3.80  42.000000  62.250000  11.370000  25.870001

[80 rows x 6 columns]

In [53]:
#Convertendo para para o formato datetime, será util para a manipulação dos dados
df_cotacoes.index = pd.to_datetime(df_cotacoes.index)

In [54]:
df_cotacoes

Ticker       BRAV3.SA  CSAN3.SA   PETR4.SA   PRIO3.SA   RECV3.SA   UGPA3.SA
Date
2026-02-02  18.298454      5.82  36.737907  50.880001  10.641539  25.870001
2026-02-03  18.139425      5.99  37.073322  51.500000  10.855536  26.110001
2026-02-04  17.940636      5.82  37.014130  50.250000  10.524813  25.990000
2026-02-05  17.483423      5.64  36.501141  49.150002  10.388633  26.120001
2026-02-06  17.374090      5.77  36.155861  50.630001  10.466450  26.670000
...               ...       ...        ...        ...        ...        ...
2026-05-25  19.930000      4.39  43.400002  64.309998  12.350000  28.440001
2026-05-26  20.070000      4.28  43.439999  64.750000  11.900000  27.870001
2026-05-27  19.910000      4.01  42.820000  62.980000  11.810000  27.480000
2026-05-28  20.240000      3.94  42.509998  62.970001  11.580000  26.910000
2026-05-29  20.250000      3.80  42.000000  62.250000  11.370000  25.870001

[80 rows x 6 columns]